permalink: /:path/:name/

collections:
  aframe: 
    title: 'Argon-aframe'
    output: true
  twine:
    title: 'Argon for Twine'
    output: true
  concepts:
    title: 'Concepts'
    output: true

# Setup
#source: code
title:               'argon.js documentation'
tagline:             'Documentation'
description:         'This site contains documentation for web developers using <a href="http://argonjs.io/design-tools" target="_blank">Design Tools</a> to add AR content to a web application.'
url:                 http://design-tools.argonjs.io
baseurl:              ''
#baseurl:             '/design-tools'
#baseurl:             'http://design-tools.argonjs.io'

argonjs: "https://rawgit.com/argonjs/argon/develop/dist/argon.js"
aframejs: "https://aframe.io/releases/0.5.0/aframe.min.js"
samples: "https://samples-develop.argonjs.io"
argonaframejs: "../build.js"

exclude: ['Rakefile', 'LICENSE.txt', 'CLA.md', 'CONTRIBUTING.md', 'README.md', "node_modules", "package.json"]
include: [code]

# About/contact
author:
  name:
  email:

# Local server settings
host: 0.0.0.0
port: 4000
